name: Labeling according to PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

permissions:
  contents: write
  pull-requests: write

jobs:
  label-from-checkbox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract checked items from PR body
        id: extract
        run: |
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_BODY=$(gh pr view "$PR_URL" --json body --template '{{.body}}')

          # Extract [X] Labels
          CHECKED=$(echo "$PR_BODY" | grep -iE '^\s*-\s*\[x\]' | sed -E 's/^\s*-\s*\[x\]\s*([^:]+):.*/\1/' | xargs)
          echo "CHECKED : $CHECKED"
          
          # Extract [ ] Labels
          UNCHECKED=$(echo "$PR_BODY" | grep -iE '^\s*-\s*\[\s\]' | sed -E 's/^\s*-\s*\[\s\]\s*([^:]+):.*/\1/' | xargs)
          echo "UNCHECKED : $UNCHECKED"
          
          echo "add_labels=$CHECKED" >> $GITHUB_OUTPUT
          echo "remove_labels=$UNCHECKED" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add checked labels
        if: steps.extract.outputs.add_labels != ''
        run: |
          labels="${{ steps.extract.outputs.add_labels }}"
          labels="${labels// /,}"
          gh pr edit "${{ github.event.pull_request.html_url }}" \
            --add-label "$labels"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove unchecked labels
        if: steps.extract.outputs.remove_labels != ''
        run: |
          labels="${{ steps.extract.outputs.remove_labels }}"
          labels="${labels// /,}"  # space → comma
          gh pr edit "${{ github.event.pull_request.html_url }}" \
            --remove-label "$labels"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}