name: Auto Edit Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened

permissions:
  contents: write
  pull-requests: write

jobs:
  edit-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract Ticket Name
        id: extract
        run: |
          branch_name="${{ github.head_ref }}"
          ticket_name="${branch_name#*/}"
          echo "ticket=$ticket_name" >> $GITHUB_OUTPUT

      - name: Get Original PR body
        id: get_body
        run: |
          pr_url="${{ github.event.pull_request.html_url }}"
          original_body=$(gh pr view "$pr_url" --json body --template '{{.body}}')
          
          if [ -z "$original_body" ]; then
          original_body="(No description provided)"
          fi
          
          echo "original<<EOF" >> $GITHUB_OUTPUT
          echo "$original_body" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Find Base branch
        id: find_base
        run: |
          git fetch --all
          current_branch="${{ github.head_ref }}"
          candidates=(main develop staging)
          base_branch=""
          
          for branch in "${candidates[@]}"; do
            git show-ref --verify --quiet "refs/remotes/origin/$branch" || continue
            merge_base=$(git merge-base "origin/$branch" HEAD)
            if git branch --contains "$merge_base" | grep -q "$current_branch"; then
              base_branch="$branch"
              break
            fi
          done
          
          echo "base branch: $base_branch"
          echo "base_branch=$base_branch" >> $GITHUB_OUTPUT

      - name: Load PR Template
        id: template
        run: |
          ticket="${{ steps.extract.outputs.ticket }}"
          original="${{ steps.get_body.outputs.original }}"
          base_branch="${{ steps.find_base.outputs.base_branch }}"
          current_branch="${{ github.head_ref }}"
          
          body=$(<.github/PULL_REQUEST_TEMPLATE.md)
          body="${body//\{original_body\}/$original}"
          body="${body//\{ticket\}/$ticket}"
          body="${body//\{base_branch\}/$base_branch}"
          body="${body//\{current_branch\}/$current_branch}"
          
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$body" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Edit PR title and body
        run: |
          echo "${{ steps.template.outputs.body }}" > pr_body.txt

          gh pr edit "${{ github.event.pull_request.html_url }}" \
            --title "feat/${{ steps.extract.outputs.ticket }}: " \
            --body "$(cat pr_body.txt)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}