name: Auto Edit Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened

permissions:
  contents: write
  pull-requests: write

jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: tzkhan/pr-update-action@v2
        with:
         repo-token: "${{ secrets.GITHUB_TOKEN }}"
         title-template: ‘[zz] '
         body-template: |
          Merging into zzzz