name: Update Jira Ticket Status

on:
  pull_request:
    types:
      - opened
      - reopened
      - closed

jobs:
  hem-open-to-under-review:
    name: "HEM: PR Open → Under Review"
    runs-on: ubuntu-latest
    if: (github.event.action == 'opened' || github.event.action == 'reopened') && contains(github.head_ref, 'HEM')
    steps:
      - name: Jira Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}

      - name: Get Ticket
        id: extract
        run: |
          echo "ticket=${${{ github.head_ref }}#*/}" >> GITHUB_OUTPUT

      - name: Update JIRA ticket to Done
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.extract.outputs.ticket }}
          transition: "Under Review"
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
        continue-on-error: true

  hem-merge-to-done:
    name: "HEM: PR Merge → Done"
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.head_ref, 'HEM')
    steps:
      - name: Jira Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}

      - name: Get Ticket
        id: extract
        run: |
          echo "ticket=${${{ github.head_ref }}#*/}" >> GITHUB_OUTPUT

      - name: Update JIRA ticket to Done
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.extract.outputs.ticket }}
          transition: "Done"
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
        continue-on-error: true

  sqa-open-to-code-review:
    name: "SQA: PR Open → Code Review"
    runs-on: ubuntu-latest
    if: (github.event.action == 'opened' || github.event.action == 'reopened') && contains(github.head_ref, 'SQA')
    steps:
      - name: Jira Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}

      - name: Get Ticket
        id: extract
        run: |
          echo "ticket=${${{ github.head_ref }}#*/}" >> GITHUB_OUTPUT

      - name: Update JIRA ticket to Code Review
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.extract.outputs.ticket }}
          transition: "Code Review"
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
        continue-on-error: true

  sqa-merge-to-under-review:
    name: "SQA: PR Merge → Under Review"
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.head_ref, 'SQA')
    steps:
      - name: Jira Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}

      - name: Get Ticket
        id: extract
        run: |
          echo "ticket=${${{ github.head_ref }}#*/}" >> GITHUB_OUTPUT

      - name: Update JIRA ticket to Under Review
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.extract.outputs.ticket }}
          transition: "Under Review"
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
        continue-on-error: true