name: Update Jira Ticket Status

on:
  pull_request:
    types:
      - opened
      - reopened
      - closed

jobs:
  update-jira:
    runs-on: ubuntu-latest

    steps:
      - name: Set HEM Jira Ticket Status → Under Review
        if: contains('SQA-4701', 'HEM') && (github.event.action == 'opened' || github.event.action == 'reopened')
        run: |
          ticket=${{ github.head_ref }}
          ticket=${ticket#*/}

          transition_id=$(curl -s -u "$JIRA_EMAIL:$JIRA_TOKEN" \
            -H "Accept: application/json" \
            "$JIRA_URL/rest/api/3/issue/$ticket/transitions" |
            jq -r '.transitions[] | select(.name == "Under Review") | .id')

          echo "Using transition ID: $transition_id"

          curl -s -X POST -u "$JIRA_EMAIL:$JIRA_TOKEN" \
            -H "Accept: application/json" -H "Content-Type: application/json" \
            --data "{ \"transition\": { \"id\": \"$transition_id\" } }" \
            "$JIRA_URL/rest/api/3/issue/$ticket/transitions"
        env:
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_URL: ${{ secrets.JIRA_URL }}

      - name: Set HEM Jira Ticket Status → Done
        if: contains('SQA-4701', 'HEM') && (github.event.action == 'closed' && github.event.pull_request.merged == true)
        run: |
          ticket=${{ github.head_ref }}
          ticket=${ticket#*/}

          transition_id=$(curl -s -u "$JIRA_EMAIL:$JIRA_TOKEN" \
            -H "Accept: application/json" \
            "$JIRA_URL/rest/api/3/issue/$ticket/transitions" |
            jq -r '.transitions[] | select(.name == "Done") | .id')

          echo "Using transition ID: $transition_id"

          curl -s -X POST -u "$JIRA_EMAIL:$JIRA_TOKEN" \
            -H "Accept: application/json" -H "Content-Type: application/json" \
            --data "{ \"transition\": { \"id\": \"$transition_id\" } }" \
            "$JIRA_URL/rest/api/3/issue/$ticket/transitions"
        env:
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_URL: ${{ secrets.JIRA_URL }}

      - name: Set SQA Jira Ticket Status → Code Review
        if: contains('SQA-4701', 'SQA') && (github.event.action == 'opened' || github.event.action == 'reopened')
        run: |
          ticket=${{ github.head_ref }}
          ticket="SQA-4701"
          
          transition_id=$(curl -s -u "$JIRA_EMAIL:$JIRA_TOKEN" \
            -H "Accept: application/json" \
            "$JIRA_URL/rest/api/3/issue/$ticket/transitions" |
            jq -r '.transitions[] | select(.name == "Code Review") | .id')
          
          echo "Using transition ID: $transition_id"
          
          curl -s -X POST -u "$JIRA_EMAIL:$JIRA_TOKEN" \
            -H "Accept: application/json" -H "Content-Type: application/json" \
            --data "{ \"transition\": { \"id\": \"$transition_id\" } }" \
            "$JIRA_URL/rest/api/3/issue/$ticket/transitions"
        env:
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_URL: ${{ secrets.JIRA_URL }}

      - name: Set SQA Jira Ticket Status → Under Review
        if: contains('SQA-4701', 'SQA') && (github.event.action == 'closed' && github.event.pull_request.merged == true)
        run: |
          ticket=${{ github.head_ref }}
          ticket="SQA-4701"
          
          transition_id=$(curl -s -u "$JIRA_EMAIL:$JIRA_TOKEN" \
            -H "Accept: application/json" \
            "$JIRA_URL/rest/api/3/issue/$ticket/transitions" |
            jq -r '.transitions[] | select(.name == "Under Review") | .id')
          
          echo "Using transition ID: $transition_id"
          
          curl -s -X POST -u "$JIRA_EMAIL:$JIRA_TOKEN" \
            -H "Accept: application/json" -H "Content-Type: application/json" \
            --data "{ \"transition\": { \"id\": \"$transition_id\" } }" \
            "$JIRA_URL/rest/api/3/issue/$ticket/transitions"
        env:
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_URL: ${{ secrets.JIRA_URL }}